// This file was autogenerated by calcdeps.py
goog.addDependency("../../soyutils_usegoog.js", ['soy', 'soy.StringBuilder'], ['goog.dom', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera3/drvemera3.js", ['drvemera3.Plugin'], ['drvemera3.view']);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera3/scripts/controller.js", ['drvemera3.controller'], ['drvemera3.model']);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera3/scripts/fixture.js", ['drvemera3.fixture'], ['goog.array']);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera3/scripts/model.js", ['drvemera3.model'], ['drvemera3.fixture']);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera3/scripts/view.js", ['drvemera3.view'], ['drvemera3.controller', 'drvemera3.model']);
goog.addDependency("../../../emax/goog/app.js", [], []);
goog.addDependency("../../../emax/goog/constants.js", ['constants'], []);
goog.addDependency("../../../emax/goog/environment.js", ['environment'], ['goog.uri.utils', 'goog.Uri']);
goog.addDependency("../../../emax/goog/router.js", ['router'], ['environment', 'goog.uri.utils', 'goog.Uri']);
goog.addDependency("../../../emax/goog/tools.js", ['tools'], []);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera3/drvemera3.tpl_ru.js", ['drvemera3.locale'], ['soy', 'soy.StringBuilder']);
